name: 08 - Using Variables

on: 
  workflow_dispatch: 
env:
  WORKFLOW_VAR: "I am a workflow var"

jobs: 
    echos:
      runs-on: ubuntu-latest
      env: 
        JOB_VAR: "I am a job env var"
        OVERWRITTEN_VAR: "I am overwritten workflow"
      steps:
        - name: Print Env Variables
          env:
            STEP_VAR: "I am a step var"
            STEP_VAR2: " I am another step var"
          run: |
            echo "Steps env var: ${{ env.STEP_VAR }}"
            echo "Step env var 2: $STEP_VAR2"
            echo "Job env var: ${{ env.JOB_VAR}}"
            echo "Workflow env var: ${{ env.WORKFLOW_VAR}}"

        - name: Print overwritten Env Variables
          env:
            OVERWRITTEN_VAR: "I am overwritten at step level"
          run: |
            echo "Steps env var: ${{ env.OVERWRITTEN_VAR }}"