name: 11-1 - Working with Inputs

on: 
  push: 
  workflow_dispatch: 
    inputs: 
      Hunt: 
        description: Hunt
        type: boolean 
        default: true
        required: true

      Offroad: 
        description: Offroad
        type: boolean 
        default: false
      target:
        description: which environment will the workflow get
        type: environment

      tag: 
        description: Release from which to build and deploy
        type: choice
        options: 
          - v1
          - v2
          - v3
        default: v3

jobs:
    set-matrix:
        runs-on: ubuntu-latest
        outputs:
          matrix: ${{ steps.set_matrix.outputs.matrix }}
        steps:
            - id: set_matrix
              run: |
                matrix_array=("Hunt")
                # if [ ${{ inputs.Hunt }} ]; then
                # matrix_array+=("Hunt")
                # fi
                if [ ${{ inputs.Offroad }} ]; then
                matrix_array+=("Offroad")
                fi
                matrix_json=$(printf '%s\n' "${matrix_array[@]}" | jq -R . | jq -s -c .)
                echo "Matrix Json: $matrix_json"
                echo "matrix=$matrix_json || [Hunt, Offroad]" >> "$GITHUB_OUTPUT"
            - name: Show matrix JSON
              run: echo "${{ steps.set_matrix.outputs.matrix }}" 

    build: 
        needs: set-matrix
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: ${{ fromJson(needs.set-matrix.outputs.matrix )}}
        steps: 
        - name: Run for
          run: | 
                echo "Running for ${{ matrix.service }}"