name: 11-1 - Working with Inputs

on: 
  workflow_dispatch: 
    inputs: 
      Hunt: 
        description: Hunt
        type: boolean 
        default: false

      another: 
        description: Offroad
        type: boolean 
        default: false
      target:
        description: which environment will the workflow get
        type: environment

      tag: 
        description: Release from which to build and deploy
        type: choice
        options: 
          - v1
          - v2
          - v3
        default: v3

jobs:
    set-matrix:
        runs-on: ubuntu-latest
        outputs:
          matrix: ${{ steps.set_matrix.outputs.matrix }}
        steps:
            - id: set_matrix
              run: |
                matrix_array = ()
                if [ ${{ inputs.Hunt }} ]; then
                matrix_array+=('"Hunt"')
                fi
                if [ ${{ inputs.Offroad }} ]; then
                matrix_array+=('"Offroad"')
                fi
                matrix_json = "[${matrix_array[*]}]"
                echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

    build: 
        needs: set-matrix
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: ${{ fromJson(needs.set-matrix.outputs.matrix )}}
        steps: 
        - name: Run for
          run: | 
                echo "Running for ${{ matrix.service }}"