name: checking workflows - aggregate
on:
    push:
    workflow_run:
        workflows: ["workflowA", "workflowB","workflowC"]
        types: 
            - completed 

jobs: 
    post-summary:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
          - name: create durations dir
            run: |
              RES_DIR="./durations"
              if [[ ! -d "./durations" ]]; then
                  mkdir -p "./durations"
              fi
          
          - name: Download all artifacts
            uses: actions/download-artifact@v4
            with: 
                path: ./durations
            
          - name: Extract map_load_time from artifacts
            run: |
                echo "### map_load_time summary" > comment.txt
                for file in ./durations/*.json; do
                    flavor=$(jq -r '.data.flavor' "$file")
                    duration=$(jq -r '.data.metrics[] | select(.metric_name == "map_load_time") | .duration' "$file")
                    echo "- **$flavoor**: \'$duration\'" >> comment.txt
                done

          - name: Upload text file
            uses: actions/upload-artifact@v4
            with:
                name: Comment txt
                path: comment.txt


