name: checking workflows - aggregate
on:
    push:

jobs: 

    call-a: 
        uses: ./.github/workflows/workflowA.yaml
    call-b: 
        uses: ./.github/workflows/workflowB.yaml
    call-c: 
        uses: ./.github/workflows/workflowC.yaml

    aggregate:
        needs: [call-a, call-b, call-c]
        runs-on: ubuntu-latest
        steps:
        #   - name: Download all artifact
        #     run: |
        #       rm ./durations
          
          - name: Download all artifacts
            uses: actions/download-artifact@v4
            with: 
                path: durations

          - name: list durations folder
            run: ls durations/

          - name: Show contents of durations
            run: |
                echo "Showing content"
                find durations || true
            
          - name: Extract map_load_time from artifacts
            run: |
                echo "### map_load_time summary" > comment.txt
                for file in durations/*/*_durations.json; do
                    echo "$file"
                    cat "$file"
                    flavor=$(jq -r '.flavor' "$file")
                    duration=$(jq -r '.metrics[] | select(.metric_name == "map_load_time") | .duration' "$file")
                    echo "- **$flavoor**: \'$duration\'" >> comment.txt
                done

          - name: Upload text file
            uses: actions/upload-artifact@v4
            with:
                name: Comment txt
                path: comment.txt

          - name: Cleanup 
            if: always() 
            run: |
             if [[ -d "durations" ]]; then
              rm -rf "durations"
              echo "cleaned up"
             fi 