name: workflowB
on:
    workflow_call: 

jobs: 
    echos:
        runs-on: ubuntu-latest
        outputs:
            artifact-name: tes-output
        steps:
            - name: create durations dir
              run: |
               RES_DIR="./durations"
               if [[ ! -d "./durations" ]]; then
                 mkdir -p "./durations"
               fi
            - name: Create b.json
              run: |
                echo '{"data": { "platform" : "iOS", "flavor": "B", "metrics":[ {"metric_name": "mycontent_load_time", "duration": "2221 ms", "test-id": "testHardCoded"},{"metric_name": "map_load_time", "duration": "2222 ms", "test-id": "testHardCodedAgain"} ] } }' > durations/B_durations.json

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: Bdurations
                path: durations/B_durations.json