name: workflowC
on:
    push:
    workflow_dispatch: 

jobs: 
    echos:
        runs-on: ubuntu-latest
        outputs:
            artifact-name: tes-output
        steps:
            - name: Create c.json
              run: |
                echo '{"data": { "platform" : "iOS", "flavor": "C", "metrics":[ {"metric_name": "mycontent_load_time", "duration": "3331 ms", "test-id": "testHardCoded"},{"metric_name": "map_load_time", "duration": "3332 ms", "test-id": "testHardCodedAgain"} ] } }' > C_durations.jso

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: C durations
                path: C_durations.json