name: workflowA
on:
    workflow_call: 

jobs: 
    echos:
        runs-on: ubuntu-latest
        outputs:
            artifact-name: tes-output
        steps:
            - name: create durations dir
              run: |
               RES_DIR="./durations"
               if [[ ! -d "./durations" ]]; then
                mkdir -p "./durations"
               fi

            - name: Create a.json
              run: |
                echo '{"data": { "platform" : "iOS", "flavor": "A", "metrics": [ {"metric_name": "mycontent_load_time", "duration": "1111 ms", "test-id": "testHardCoded"},{"metric_name": "map_load_time", "duration": "1112 ms", "test-id": "testHardCodedAgain"} ] } }' > durations/A_durations.json

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: A_durations.json
                path: durations/A_durations.json